---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cfs-log-receiver-data
  namespace: cfs-log-viewer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # storageClassName: my-storage-class  # uncomment and set if needed
