apiVersion: v1
kind: Service
metadata:
  name: cfs-log-receiver
  labels:
    app: cfs-log-receiver
spec:
  selector:
    app: cfs-log-receiver
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
